config/routes.rb
Answerbox::Application.routes.draw do

  devise_for :users,:skip => [:sessions,:confirmations,:passwords,:registrations],:controllers => {:omniauth_callbacks => "users/omniauth_callbacks",:sessions => "sessions"} do
    get '/logout' => 'sessions#destroy', :as => :destroy_user_session
    get '/login' => 'sessions#new', :as => :new_user_session
  end

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end



  resources :questions, only: [:show, :index, :new, :create] do
    resources :answers, only: [:new, :create]
    collection do
      post :filter
    end
  end

  resources :answers do
    member do
      post :mark_as_checked
      post :create_comment
    end
  end

  resources :tags, only: [:index]

  root :to => "questions#index"
end

app/models/question.rb
class Question < ActiveRecord::Base

  attr_accessor   :tags_list
  attr_accessible :body, :title, :user_id, :tags_list,:rendered_body

  belongs_to :user
  has_many :answers,:dependent => :destroy
  has_and_belongs_to_many :tags

  validates :title, presence: true, length: { in: 10..150 }
  validates :body, presence: true, length: { minimum: 1 }

  validate :user_can_ask_question
  validate :user_needs_to_wait_5_minutes

  before_save :render_body
  before_create :create_tags
  after_create :remove_points

  COST = 1

  def answered?
    self.answers.detect(&:answered?)
  end

  def owner?(current_user)
    self.user_id == current_user.id
  end

  def tags?
    self.tags.present?
  end

  def tags_names
    tags.collect(&:name).join(", ")
  end


  #  scope :with_tag, lambda { |tag_name| includes(:tags).where("tags.name LIKE ?", "#{tag_name}%") }
  def self.with_tag_or_name(search)
    if search.present?
      #joins(:tags).where("tags.name LIKE ? OR title LIKE ?", "#{search}%", "%#{search}%").uniq
      joins("LEFT JOIN 'questions_tags' on questions.id = questions_tags.question_id LEFT JOIN 'tags' on tags.id = questions_tags.tag_id")
      .where("tags.name LIKE ? or TITLE like ?","%#{search}%","%#{search}%").uniq
    else
      Question.scoped
    end
  end

  private
  def user_needs_to_wait_5_minutes
    seconds_to_wait = 1.second;#1.minutes
    most_recent_question = self.user.questions.order("created_at DESC").first
    if most_recent_question
      if (Time.now - most_recent_question.created_at).seconds < seconds_to_wait
        errors[:body] << "You need to wait #{seconds_to_wait} seconds before you can ask another question"
      end
    end
  end

  def user_can_ask_question
    self.errors[:body] << "Not enough points to ask a question" unless self.user.can_ask_question?
  end

  def remove_points
    self.user.change_points!(-COST)
  end

  def render_body
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    self.rendered_body = redcarpet.render(self.body)
  end

  def create_tags
    if self.tags_list.present?
      tags_names = self.tags_list.split(",")
      tags_names.each do |tag_name|
        tag_name = tag_name.strip
        tag = Tag.find_or_create_by_name(tag_name)
        self.tags << tag
      end
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authenticate_user!, except: [:index,:show,:filter]

  def index
    @questions = Question.paginate(:page => params[:page],:per_page => 10)
  end
  
  def new
    @question = current_user.questions.build
  end

  def create
    @question = current_user.questions.build(params[:question])
    if @question.save
      Notifier.instance.broadcast_message("/questions",{:title => @question.title })
      flash[:info] = "Question was saved"
      redirect_to @question
    else
      render "new"
    end
  end

  def show
    @question = Question.find(params[:id])
    @owner = current_user ? @question.owner?(current_user) : false
  end

  def filter
    @questions = Question.with_tag_or_name(params[:search])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer.html.haml
%div.well.well-small
  .media
    .pull-left
      %img.media-object.small{:src => answer.user.avatar.url}
    .media-body
      .control-group
        = answer.rendered_body.html_safe
        %br
        %br
        - if @owner && !answer.question.answered?
          = link_to "This is answer!", mark_as_checked_answer_path(answer), method: :post
        - if answer.answered?
          %i.icon-ok
        - if current_user
          = render partial: "questions/comment_form", locals: { answer: answer }
  %h5 Comments
  #answer_comments
    %ul.nav.nav-list#answer_list
      = render partial: "answers/comment", collection: answer.comments
%li.divider   

app/views/questions/_answer_form.html.haml
= form_for :answer, url: question_answers_path(@question), remote: true, html: { class: "form-horizontal", id: "answer-form"}do |f|
  %fieldset
    .control-group
      = f.label "Your answer: "
    .control-group{:class => (@answer && @answer.errors[:body].length > 0) ? "error" : ""}
      = f.text_area :body, :rows => 3,:style => "width:900px"
      %span.help-inline.answer-errors
    .control-group.pull-right
      - if @owner
        = f.submit "Answer now", class: "btn", confirm: "Are you sure you want to answer your own question?",:class => "btn btn-primary"
      - else
        = f.submit "Answer now", class: "btn",:class => "btn btn-primary"

app/views/questions/_comment_form.html.haml
= form_for :comment, url: create_comment_answer_path(answer), remote: true, html: {id: "comment-form"} do |f|
  .control-group
    = f.text_field :comment, placeholder: "Comment",:id => :comment_body
    %span.help-block#comment_errors
  .control-group
    = f.submit "add"

app/views/questions/_question.html.haml
.well.well-small
  %h4
    %a{:href => question_path(question)}
      - if question.answered?
        %i.icon-ok
      = question.title
    - if question.tags?
      %p
        %strong Tags:
        = question.tags_names

app/views/questions/filter.js.erb
$("#questions").html("<%= escape_javascript render(partial: "question", collection: @questions) %>");

app/views/questions/index.html.haml
.container-fluid.index{:style => "max-width: 900px; margin: 0 auto;"}
  .ui-widget
    = label_tag "tags or name"
    = text_field_tag "tags"
  #questions 
    = render partial: "question", collection: @questions
  .row-fluid
    .span12
      .row-fluid
      .row-fluid
  %div{:style => "display:none"}
    = will_paginate @questions

app/views/questions/index.js.erb
$('#questions').append('<%= j render(@questions) %>');
<% if @questions.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@questions) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/questions/new.html.haml
.well.well-small(style="overflow:auto")
  = form_for(@question,:class => "form-horizontal") do |f|
    %fieldset
      %legend Title

      %div.control-group{:class => @question.errors[:title].length > 0 ? "error" : ""}
        %div.controls
          = f.text_field :title,:placeholder => "Question title ...",:style => "width:98%"
          - if @question.errors[:title].length > 0
            %span.help-inline= @question.errors[:title].last

    %fieldset
      %legend Description

      %div.control-group{:class => @question.errors[:body].length > 0 ? "error" : ""}
        %div.controls
          = f.text_area :body, :placeholder => "Question body here...",:rows => 5,:style => "width:98%"
          - if @question.errors[:body].length > 0
            %span.help-inline= @question.errors[:body].last

    %fieldset
      %legend Tags
      %div.controls
        = f.text_field :tags_list, value: "",placeholder: "Put your tags here, separated by comma",:style => "width:98%;"
    %p.pull-right
      %button(type="submit" class="btn btn-primary" style="margin:10px 3px 0px 0px") Ask question

app/views/questions/show.html.haml
.well.well-small{:"data-question" => @question.id}
  .media
    .pull-left
      %img.media-object.small{:src => @question.user.avatar.url}
    .media-body
      %h4.media-heading
        %a{:href => question_path(@question)}= @question.title
      %p= @question.rendered_body.html_safe
- if @answers.present?
  %h4 Answers
%ul#answers.all_answers.nav.nav-list
  = render partial: "answer", collection: @question.answers

- unless @question.answered? || !current_user
  #answer-form
    = render partial: "answer_form"